sudo: required
services: 
  - docker
language: generic
env:
  global:
    - BUILD_NUM=$TRAVIS_JOB_ID
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install: 
  - openssl aes-256-cbc -K $encrypted_74d4f3573c88_key -iv $encrypted_74d4f3573c88_iv -in muti-k8s-308317-74e11af45910.json.enc -out muti-k8s-308317-74e11af45910.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file muti-k8s-308317-74e11af45910.json
  - gcloud config set project muti-k8s-308317
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials multi-k8s
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

 
deploy:
    provider: script
    script: bash ./deploy.sh
    on:
      branch: master
  
  
